allow for debian and fedora paths

diff --git a/scripts/osm-fixes/fix-osm b/scripts/osm-fixes/fix-osm
--- a/scripts/osm-fixes/fix-osm
+++ b/scripts/osm-fixes/fix-osm
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-IIAB=/usr/lib/python2.7/site-packages/iiab
+if [ -d "/usr/lib/python2.7/site-packages/iiab" ]; then
+  IIAB=/usr/lib/python2.7/site-packages/iiab
+elif [ -d "/usr/local/lib/python2.7/dist-packages/iiab" ]; then
+  IIAB=/usr/lib/python2.7/dist-packages/iiab
+else
+  echo "IIAB not found."
+  exit 1
+fi
 
 cp etc.iiab.conf /etc/iiab.conf
 cp -f map_search.py $IIAB
